name: play_store_scraper
description: A flutter package to scrape data from the Google Play Store.
version: 0.0.1
homepage: https://github.com/ankushmishra2903-official/play_store_scraper
issue_tracker: https://github.com/ankushmishra2903-official/play_store_scraper/issues
repository: https://github.com/ankushmishra2903-official/play_store_scraper

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  web_scraper: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter: